name: Performance Testing

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 3 * * *'  # Daily at 3 AM
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  performance-benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build API
        run: pnpm --filter @jewelry-seo/api build

      - name: Start API server
        run: |
          PORT=3001 DATABASE_URL=./test.sqlite node apps/api/dist/server.js &
          sleep 10

      - name: Create results directory
        run: mkdir -p apps/performance/results
      - name: Run API performance tests
        run: pnpm --filter @jewelry-seo/performance test:api
        env:
          BASE_URL: http://localhost:3001
        continue-on-error: true

      - name: Run load tests
        run: pnpm --filter @jewelry-seo/performance test:load
        env:
          BASE_URL: http://localhost:3001
        continue-on-error: true

      - name: Upload performance results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-results
          path: |
            apps/performance/results/
            performance-results/
            !apps/performance/results/node_modules/

      - name: Generate performance report
        if: always()
        run: |
          # Generate performance summary
          echo "# Performance Test Results" > performance-report.md
          echo "Generated on: $(date)" >> performance-report.md
          echo "" >> performance-report.md
          echo "## API Performance" >> performance-report.md
          echo "API response times and throughput metrics" >> performance-report.md
          echo "" >> performance-report.md
          echo "## Load Testing" >> performance-report.md
          echo "Concurrency and scalability results" >> performance-report.md

      - name: Upload performance report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-report
          path: performance-report.md

  frontend-performance:
    name: Frontend Performance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build web application
        run: pnpm --filter @jewelry-seo/web build

      - name: Start web server
        run: |
          cd apps/web/dist && python3 -m http.server 4000 &
          sleep 5

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: './.github/lighthouse-config.json'
          urls: |
            http://localhost:4000/
            http://localhost:4000/products
            http://localhost:4000/analytics
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Upload Lighthouse results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-results
          path: |
            lighthouse-results/
            .lighthouseci/

  bundle-analysis:
    name: Bundle Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build applications
        run: |
          pnpm --filter @jewelry-seo/api build
          pnpm --filter @jewelry-seo/web build

      - name: Create bundle analysis directory
        run: mkdir -p bundle-sizes
      - name: Analyze bundle sizes
        run: |
          # Analyze API bundle
          echo "## API Bundle Analysis" > bundle-analysis.md
          echo "\`\`\`" >> bundle-analysis.md
          ls -la apps/api/dist/ >> bundle-analysis.md
          echo "\`\`\`" >> bundle-analysis.md

          # Create detailed bundle size report
          apps/api/dist >> bundle-sizes/api-bundle.txt 2>/dev/null || echo "No API bundle found" > bundle-sizes/api-bundle.txt

          # Analyze web bundle
          echo "## Web Bundle Analysis" >> bundle-analysis.md
          echo "\`\`\`" >> bundle-analysis.md
          ls -la apps/web/dist/ >> bundle-analysis.md
          echo "\`\`\`" >> bundle-analysis.md

          # Create detailed web bundle report
          find apps/web/dist -name "*.js" -exec ls -la {} \; > bundle-sizes/web-bundle.txt 2>/dev/null || echo "No web bundle found" > bundle-sizes/web-bundle.txt

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bundle-analysis
          path: |
            bundle-analysis.md
            bundle-sizes/

      - name: Check bundle size thresholds
        run: |
          # Add bundle size checking logic here
          echo "Checking bundle size thresholds..."
          if [ -f "apps/web/dist/assets/index-*.js" ]; then
            bundle_size=$(stat -c%s apps/web/dist/assets/index-*.js)
            echo "Web bundle size: $bundle_size bytes"
            if [ $bundle_size -gt 1048576 ]; then  # 1MB
              echo "Warning: Web bundle exceeds 1MB"
            fi
          fi